name: resume-backend-pipeline

on:
  push:
    
    branches:
      - main

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Set up Python 
        uses: actions/setup-python@2
        with:
          python-version: 3.9 
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt    

      - name: Run test 
        run:  |
          pytest

  deploy-s3: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region 
      
      - name: Deploy code to s3 
        run: | 
          aws s3 sync lambda_code/index.py s3://robudexbucket    
        


# name: Deploy Terraform Stack

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1

#       - name: Set up AWS CLI
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: your-region  # Replace with your AWS region

#       - name: Initialize Terraform
#         run: terraform init

#       - name: Apply Terraform Changes
#         run: terraform apply -auto-approve
#         env:
#           TF_VAR_region: your-region  # Replace with your AWS region
